// <auto-generated />
using System;
using GradGateway.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradGateway.Data.Migrations
{
    [DbContext(typeof(GradGatewayDbContext))]
    [Migration("20260227114010_SeedMoreSriLankanData")]
    partial class SeedMoreSriLankanData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GradGateway.Data.Entities.CompanyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoDataUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CompanyProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-1111-2222-3333-444444444444"),
                            CompanyEmail = "careers@demotech.lk",
                            CompanyName = "Demo Technologies (Pvt) Ltd",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Software & IT",
                            Phone = "+94114567890",
                            Position = "HR Manager",
                            RecruiterEmail = "anjana@demotech.lk",
                            RecruiterName = "Anjana Silva",
                            RecruiterPhone = "+94770111222",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("66666666-7777-8888-9999-aaaaaaaaaaaa"),
                            Website = "https://demotech.lk"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-2222-3333-555555555555"),
                            CompanyEmail = "talent@dialog.lk",
                            CompanyName = "Dialog Axiata PLC",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Telecommunications",
                            Phone = "+94117722345",
                            Position = "Talent Acquisition Executive",
                            RecruiterEmail = "kasun.rodrigo@dialog.lk",
                            RecruiterName = "Kasun Rodrigo",
                            RecruiterPhone = "+94771239876",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("66666666-7777-8888-9999-bbbbbbbbbbbb"),
                            Website = "https://www.dialog.lk"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-2222-3333-666666666666"),
                            CompanyEmail = "campus@wso2.com",
                            CompanyName = "WSO2 Lanka (Pvt) Ltd",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Software & IT",
                            Phone = "+94112678901",
                            Position = "Campus Recruiter",
                            RecruiterEmail = "ishara.fernando@wso2.com",
                            RecruiterName = "Ishara Fernando",
                            RecruiterPhone = "+94712340987",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("66666666-7777-8888-9999-cccccccccccc"),
                            Website = "https://wso2.com"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-2222-3333-777777777777"),
                            CompanyEmail = "university.relations@virtusa.com",
                            CompanyName = "Virtusa (Pvt) Ltd",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Software & IT",
                            Phone = "+94117890123",
                            Position = "Associate Manager - Talent",
                            RecruiterEmail = "dinithi.abeywickrama@virtusa.com",
                            RecruiterName = "Dinithi Abeywickrama",
                            RecruiterPhone = "+94770123456",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("66666666-7777-8888-9999-dddddddddddd"),
                            Website = "https://www.virtusa.com"
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gpa")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("GradYear")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoDataUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-2222-3333-444444444444"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Degree = "BSc (Hons) in IT",
                            FullName = "Demo Student",
                            Gpa = 3.45m,
                            GradYear = 2027,
                            Phone = "+94771234567",
                            StudentId = "UOM2024001",
                            University = "University of Moratuwa",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-2222-3333-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Degree = "BSc Engineering",
                            FullName = "Nethmi Perera",
                            Gpa = 3.82m,
                            GradYear = 2026,
                            Phone = "+94712223344",
                            StudentId = "PDN2023123",
                            University = "University of Peradeniya",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-2222-3333-4444-666666666666")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-2222-3333-666666666666"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Degree = "BSc (Hons) in Computer Science",
                            FullName = "Sahan Jayasinghe",
                            Gpa = 3.67m,
                            GradYear = 2025,
                            Phone = "+94773334455",
                            StudentId = "UOC2022110",
                            University = "University of Colombo",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-2222-3333-4444-777777777777")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-2222-3333-777777777777"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Degree = "BSc in Information Technology",
                            FullName = "Tharushi Senanayake",
                            Gpa = 3.29m,
                            GradYear = 2027,
                            Phone = "+94764445566",
                            StudentId = "UOJ2023567",
                            University = "University of Jaffna",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-2222-3333-4444-888888888888")
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gradgateway.com",
                            FirebaseUid = "CffvlJMXIlUM3FRQzNyu80hXBkU2",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student.demo@uom.lk",
                            FirebaseUid = "demo-student-uid-001",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-666666666666"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nethmi.perera@eng.pdn.ac.lk",
                            FirebaseUid = "demo-student-uid-002",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-777777777777"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sahan.jayasinghe@stu.cmb.ac.lk",
                            FirebaseUid = "demo-student-uid-003",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-888888888888"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tharushi.senanayake@jfn.ac.lk",
                            FirebaseUid = "demo-student-uid-004",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-7777-8888-9999-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "company.demo@sample.lk",
                            FirebaseUid = "demo-company-uid-001",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-7777-8888-9999-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "careers@dialog.lk",
                            FirebaseUid = "demo-company-uid-002",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-7777-8888-9999-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "internships@wso2.com",
                            FirebaseUid = "demo-company-uid-003",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-7777-8888-9999-dddddddddddd"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hr@virtusa.com",
                            FirebaseUid = "demo-company-uid-004",
                            Role = 2
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.CompanyProfile", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.StudentProfile", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
