// <auto-generated />
using System;
using GradGateway.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradGateway.Data.Migrations
{
    [DbContext(typeof(GradGatewayDbContext))]
    partial class GradGatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GradGateway.Data.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CompanyProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Compensation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InterviewPlanNotifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("OpportunityId", "StudentProfileId")
                        .IsUnique()
                        .HasFilter("[OpportunityId] IS NOT NULL");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-1111-2222-3333-444444444444"),
                            AppliedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoverLetter = "I am eager to contribute to ASP.NET Core projects and learn from your team.",
                            OpportunityId = new Guid("dddddddd-1111-2222-3333-444444444444"),
                            Status = 0,
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-444444444444"),
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-1111-2222-3333-555555555555"),
                            AppliedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoverLetter = "My data analytics coursework and projects align with this opportunity.",
                            OpportunityId = new Guid("dddddddd-1111-2222-3333-555555555555"),
                            Status = 1,
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-555555555555"),
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-1111-2222-3333-666666666666"),
                            AppliedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoverLetter = "I have strong backend foundations and cloud fundamentals.",
                            OpportunityId = new Guid("dddddddd-1111-2222-3333-666666666666"),
                            Status = 0,
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-666666666666"),
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.CompanyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoDataUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CompanyProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-1111-2222-3333-444444444444"),
                            CompanyEmail = "careers@demotech.lk",
                            CompanyName = "Demo Technologies (Pvt) Ltd",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Software & IT",
                            Phone = "+94114567890",
                            Position = "HR Manager",
                            RecruiterEmail = "anjana@demotech.lk",
                            RecruiterName = "Anjana Silva",
                            RecruiterPhone = "+94770111222",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("66666666-7777-8888-9999-aaaaaaaaaaaa"),
                            Website = "https://demotech.lk"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-2222-3333-555555555555"),
                            CompanyEmail = "talent@dialog.lk",
                            CompanyName = "Dialog Axiata PLC",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Telecommunications",
                            Phone = "+94117722345",
                            Position = "Talent Acquisition Executive",
                            RecruiterEmail = "kasun.rodrigo@dialog.lk",
                            RecruiterName = "Kasun Rodrigo",
                            RecruiterPhone = "+94771239876",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("66666666-7777-8888-9999-bbbbbbbbbbbb"),
                            Website = "https://www.dialog.lk"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-2222-3333-666666666666"),
                            CompanyEmail = "campus@wso2.com",
                            CompanyName = "WSO2 Lanka (Pvt) Ltd",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Software & IT",
                            Phone = "+94112678901",
                            Position = "Campus Recruiter",
                            RecruiterEmail = "ishara.fernando@wso2.com",
                            RecruiterName = "Ishara Fernando",
                            RecruiterPhone = "+94712340987",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("66666666-7777-8888-9999-cccccccccccc"),
                            Website = "https://wso2.com"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-2222-3333-777777777777"),
                            CompanyEmail = "university.relations@virtusa.com",
                            CompanyName = "Virtusa (Pvt) Ltd",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Software & IT",
                            Phone = "+94117890123",
                            Position = "Associate Manager - Talent",
                            RecruiterEmail = "dinithi.abeywickrama@virtusa.com",
                            RecruiterName = "Dinithi Abeywickrama",
                            RecruiterPhone = "+94770123456",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("66666666-7777-8888-9999-dddddddddddd"),
                            Website = "https://www.virtusa.com"
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.CompanyTeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompanyProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("InvitationExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("InvitationToken")
                        .IsUnique();

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("CompanyProfileId", "Email")
                        .IsUnique();

                    b.ToTable("CompanyTeamMembers");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abababab-1111-2222-3333-444444444444"),
                            CompanyProfileId = new Guid("cccccccc-1111-2222-3333-444444444444"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastMessageAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OpportunityId = new Guid("dddddddd-1111-2222-3333-444444444444"),
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-444444444444")
                        },
                        new
                        {
                            Id = new Guid("abababab-1111-2222-3333-555555555555"),
                            CompanyProfileId = new Guid("cccccccc-1111-2222-3333-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastMessageAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OpportunityId = new Guid("dddddddd-1111-2222-3333-555555555555"),
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-555555555555")
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FileType");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2b2b2b2-1111-2222-3333-444444444444"),
                            FileName = "Demo_Student_CV.pdf",
                            FileType = "CV",
                            FileUrl = "https://storage.gradgateway.lk/docs/demo-student-cv.pdf",
                            IsPublic = false,
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-444444444444"),
                            UploadedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-1111-2222-3333-555555555555"),
                            FileName = "Nethmi_Perera_Transcript.pdf",
                            FileType = "Transcript",
                            FileUrl = "https://storage.gradgateway.lk/docs/nethmi-transcript.pdf",
                            IsPublic = false,
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-555555555555"),
                            UploadedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-1111-2222-3333-666666666666"),
                            FileName = "Sahan_Portfolio.pdf",
                            FileType = "Portfolio",
                            FileUrl = "https://storage.gradgateway.lk/docs/sahan-portfolio.pdf",
                            IsPublic = true,
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-666666666666"),
                            UploadedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Interview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("ScheduledAt");

                    b.ToTable("Interviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b1b1b1-1111-2222-3333-444444444444"),
                            ApplicationId = new Guid("eeeeeeee-1111-2222-3333-444444444444"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MeetingLink = "https://meet.google.com/demo-gradgateway-1",
                            Mode = 0,
                            Notes = "First-round technical interview",
                            ScheduledAt = new DateTime(2026, 3, 10, 4, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b1b1b1b1-1111-2222-3333-555555555555"),
                            ApplicationId = new Guid("eeeeeeee-1111-2222-3333-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Dialog HQ, Battaramulla",
                            Mode = 1,
                            Notes = "Case study and discussion",
                            ScheduledAt = new DateTime(2026, 3, 12, 5, 30, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("SentAt");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("acacacac-1111-2222-3333-444444444444"),
                            Content = "Good morning, I submitted my application. Could you share the interview timeline?",
                            ConversationId = new Guid("abababab-1111-2222-3333-444444444444"),
                            IsRead = true,
                            SenderUserId = new Guid("11111111-2222-3333-4444-555555555555"),
                            SentAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("acacacac-1111-2222-3333-555555555555"),
                            Content = "Thanks! Shortlisting will be completed by next week.",
                            ConversationId = new Guid("abababab-1111-2222-3333-444444444444"),
                            IsRead = true,
                            SenderUserId = new Guid("66666666-7777-8888-9999-aaaaaaaaaaaa"),
                            SentAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("acacacac-1111-2222-3333-666666666666"),
                            Content = "Please upload your updated CV and transcript.",
                            ConversationId = new Guid("abababab-1111-2222-3333-555555555555"),
                            IsRead = false,
                            SenderUserId = new Guid("66666666-7777-8888-9999-bbbbbbbbbbbb"),
                            SentAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RelatedOpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedStudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("adadadad-1111-2222-3333-444444444444"),
                            Body = "Your application for Software Engineering Intern was submitted successfully.",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Title = "Application Submitted",
                            Type = 1,
                            UserId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            Id = new Guid("adadadad-1111-2222-3333-555555555555"),
                            Body = "You have been shortlisted for Data Analytics Intern at Dialog Axiata PLC.",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Title = "Application Shortlisted",
                            Type = 1,
                            UserId = new Guid("11111111-2222-3333-4444-666666666666")
                        },
                        new
                        {
                            Id = new Guid("adadadad-1111-2222-3333-666666666666"),
                            Body = "You received a new message from Demo Student.",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Title = "New Candidate Message",
                            Type = 3,
                            UserId = new Guid("66666666-7777-8888-9999-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadlineAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeadlineNotificationSent")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MonthlyStipendLkr")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("OpportunityType")
                        .HasColumnType("int");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId");

                    b.HasIndex("DeadlineAt");

                    b.ToTable("Opportunities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-1111-2222-3333-444444444444"),
                            CompanyProfileId = new Guid("cccccccc-1111-2222-3333-444444444444"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeadlineAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeadlineNotificationSent = false,
                            Description = "Internship for 3rd year undergraduates with C# and React exposure.",
                            IsActive = true,
                            Location = "Colombo 03",
                            MonthlyStipendLkr = 75000m,
                            OpportunityType = 0,
                            RequiredSkills = "C#, ASP.NET Core, React, SQL Server",
                            Title = "Software Engineering Intern",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkMode = 1
                        },
                        new
                        {
                            Id = new Guid("dddddddd-1111-2222-3333-555555555555"),
                            CompanyProfileId = new Guid("cccccccc-1111-2222-3333-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeadlineAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeadlineNotificationSent = false,
                            Description = "Hands-on analytics internship with telecom datasets and Power BI.",
                            IsActive = true,
                            Location = "Battaramulla",
                            MonthlyStipendLkr = 85000m,
                            OpportunityType = 0,
                            RequiredSkills = "Python, SQL, Power BI, Statistics",
                            Title = "Data Analytics Intern",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkMode = 0
                        },
                        new
                        {
                            Id = new Guid("dddddddd-1111-2222-3333-666666666666"),
                            CompanyProfileId = new Guid("cccccccc-1111-2222-3333-666666666666"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeadlineAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeadlineNotificationSent = false,
                            Description = "Entry-level role for fresh graduates interested in cloud-native development.",
                            IsActive = true,
                            Location = "Colombo 07",
                            MonthlyStipendLkr = 180000m,
                            OpportunityType = 1,
                            RequiredSkills = "Java, Microservices, Docker, Kubernetes",
                            Title = "Associate Software Engineer",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkMode = 1
                        },
                        new
                        {
                            Id = new Guid("dddddddd-1111-2222-3333-777777777777"),
                            CompanyProfileId = new Guid("cccccccc-1111-2222-3333-777777777777"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeadlineAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeadlineNotificationSent = false,
                            Description = "Internship focused on test automation for enterprise applications.",
                            IsActive = true,
                            Location = "Sri Lanka",
                            MonthlyStipendLkr = 70000m,
                            OpportunityType = 0,
                            RequiredSkills = "Selenium, Playwright, C#, CI/CD",
                            Title = "QA Automation Intern",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkMode = 2
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.OpportunityInterviewPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TentativeDatesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId")
                        .IsUnique();

                    b.ToTable("OpportunityInterviewPlans");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DemoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aeaeaeae-1111-2222-3333-444444444444"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DemoUrl = "https://portfolio.demo.lk/gradgateway",
                            Description = "A full-stack web platform for student recruitment workflow.",
                            IsPublic = true,
                            RepositoryUrl = "https://github.com/demo/gradgateway-portfolio",
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-444444444444"),
                            TechStack = "Next.js, ASP.NET Core, SQL Server",
                            Title = "GradGateway Portfolio",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aeaeaeae-1111-2222-3333-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Data analytics dashboard for Sri Lankan intercity bus utilization.",
                            IsPublic = true,
                            RepositoryUrl = "https://github.com/demo/lanka-bus-analytics",
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-555555555555"),
                            TechStack = "Python, Power BI, PostgreSQL",
                            Title = "Lanka Bus Analytics",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aeaeaeae-1111-2222-3333-666666666666"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DemoUrl = "https://eventhub.demo.lk",
                            Description = "Mobile-first event management system for university societies.",
                            IsPublic = true,
                            RepositoryUrl = "https://github.com/demo/campus-event-hub",
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-666666666666"),
                            TechStack = "React Native, Firebase, Node.js",
                            Title = "Campus Event Hub",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.ProjectImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectImages");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.SavedOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("StudentProfileId", "OpportunityId")
                        .IsUnique();

                    b.ToTable("SavedOpportunities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-1111-2222-3333-444444444444"),
                            OpportunityId = new Guid("dddddddd-1111-2222-3333-555555555555"),
                            SavedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-444444444444")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-1111-2222-3333-555555555555"),
                            OpportunityId = new Guid("dddddddd-1111-2222-3333-777777777777"),
                            SavedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-777777777777")
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afafafaf-1111-2222-3333-444444444444"),
                            Category = "Backend",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("afafafaf-1111-2222-3333-555555555555"),
                            Category = "Backend",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = new Guid("afafafaf-1111-2222-3333-666666666666"),
                            Category = "Frontend",
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("afafafaf-1111-2222-3333-777777777777"),
                            Category = "Database",
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = new Guid("afafafaf-1111-2222-3333-888888888888"),
                            Category = "Data",
                            Name = "Power BI"
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwardsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentYear")
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldOfMajor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gpa")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("GradYear")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoDataUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-2222-3333-444444444444"),
                            Availability = "Available Now",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentYear = 0,
                            Degree = "BSc (Hons) in IT",
                            FieldOfMajor = "",
                            FullName = "Demo Student",
                            Gpa = 3.45m,
                            GradYear = 2027,
                            Phone = "+94771234567",
                            StudentId = "UOM2024001",
                            University = "University of Moratuwa",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-2222-3333-555555555555"),
                            Availability = "Available Now",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentYear = 0,
                            Degree = "BSc Engineering",
                            FieldOfMajor = "",
                            FullName = "Nethmi Perera",
                            Gpa = 3.82m,
                            GradYear = 2026,
                            Phone = "+94712223344",
                            StudentId = "PDN2023123",
                            University = "University of Peradeniya",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-2222-3333-4444-666666666666")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-2222-3333-666666666666"),
                            Availability = "Available Now",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentYear = 0,
                            Degree = "BSc (Hons) in Computer Science",
                            FieldOfMajor = "",
                            FullName = "Sahan Jayasinghe",
                            Gpa = 3.67m,
                            GradYear = 2025,
                            Phone = "+94773334455",
                            StudentId = "UOC2022110",
                            University = "University of Colombo",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-2222-3333-4444-777777777777")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-2222-3333-777777777777"),
                            Availability = "Available Now",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentYear = 0,
                            Degree = "BSc in Information Technology",
                            FieldOfMajor = "",
                            FullName = "Tharushi Senanayake",
                            Gpa = 3.29m,
                            GradYear = 2027,
                            Phone = "+94764445566",
                            StudentId = "UOJ2023567",
                            University = "University of Jaffna",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-2222-3333-4444-888888888888")
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.StudentSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("StudentProfileId", "SkillId")
                        .IsUnique();

                    b.ToTable("StudentSkills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0b0b0b0-1111-2222-3333-444444444444"),
                            ProficiencyLevel = 2,
                            SkillId = new Guid("afafafaf-1111-2222-3333-444444444444"),
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-444444444444"),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = new Guid("b0b0b0b0-1111-2222-3333-555555555555"),
                            ProficiencyLevel = 1,
                            SkillId = new Guid("afafafaf-1111-2222-3333-555555555555"),
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-444444444444"),
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = new Guid("b0b0b0b0-1111-2222-3333-666666666666"),
                            ProficiencyLevel = 2,
                            SkillId = new Guid("afafafaf-1111-2222-3333-888888888888"),
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-555555555555"),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = new Guid("b0b0b0b0-1111-2222-3333-777777777777"),
                            ProficiencyLevel = 2,
                            SkillId = new Guid("afafafaf-1111-2222-3333-666666666666"),
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-666666666666"),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = new Guid("b0b0b0b0-1111-2222-3333-888888888888"),
                            ProficiencyLevel = 1,
                            SkillId = new Guid("afafafaf-1111-2222-3333-777777777777"),
                            StudentProfileId = new Guid("bbbbbbbb-1111-2222-3333-666666666666"),
                            YearsOfExperience = 2
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gradgateway.com",
                            FirebaseUid = "CffvlJMXIlUM3FRQzNyu80hXBkU2",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student.demo@uom.lk",
                            FirebaseUid = "demo-student-uid-001",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-666666666666"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nethmi.perera@eng.pdn.ac.lk",
                            FirebaseUid = "demo-student-uid-002",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-777777777777"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sahan.jayasinghe@stu.cmb.ac.lk",
                            FirebaseUid = "demo-student-uid-003",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-888888888888"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tharushi.senanayake@jfn.ac.lk",
                            FirebaseUid = "demo-student-uid-004",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-7777-8888-9999-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "company.demo@sample.lk",
                            FirebaseUid = "demo-company-uid-001",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-7777-8888-9999-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "careers@dialog.lk",
                            FirebaseUid = "demo-company-uid-002",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-7777-8888-9999-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "internships@wso2.com",
                            FirebaseUid = "demo-company-uid-003",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-7777-8888-9999-dddddddddddd"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hr@virtusa.com",
                            FirebaseUid = "demo-company-uid-004",
                            Role = 2
                        });
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Application", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.CompanyProfile", "CompanyProfile")
                        .WithMany()
                        .HasForeignKey("CompanyProfileId");

                    b.HasOne("GradGateway.Data.Entities.Opportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GradGateway.Data.Entities.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyProfile");

                    b.Navigation("Opportunity");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.CompanyProfile", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.CompanyTeamMember", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.CompanyProfile", "CompanyProfile")
                        .WithMany()
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradGateway.Data.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyProfile");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Conversation", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.CompanyProfile", "CompanyProfile")
                        .WithMany()
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradGateway.Data.Entities.Opportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradGateway.Data.Entities.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyProfile");

                    b.Navigation("Opportunity");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Document", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.EmailLog", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Interview", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Message", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradGateway.Data.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Notification", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Opportunity", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.CompanyProfile", "CompanyProfile")
                        .WithMany()
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.OpportunityInterviewPlan", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.Opportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Project", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.ProjectImage", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.SavedOpportunity", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.Opportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradGateway.Data.Entities.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.StudentProfile", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.StudentSkill", b =>
                {
                    b.HasOne("GradGateway.Data.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradGateway.Data.Entities.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("GradGateway.Data.Entities.Project", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
